changelog:
    exclude:
        authors:
            - github-actions[bot]
    categories:
        - title: "🚀 Features"
          labels:
              - feature
          rewrite:
              title_is_enough: true
          filter:
              commit-expressions:
                  - '^feat(\(.*\))?:'
                  - '^feature(\(.*\))?:'

        - title: "🐛 Bug Fixes"
          labels:
              - bug
          filter:
              commit-expressions:
                  - '^fix(\(.*\))?:'

        - title: "🔧 Maintenance"
          filter:
              commit-expressions:
                  - '^chore(\(.*\))?:'
                  - '^docs(\(.*\))?:'
                  - '^refactor(\(.*\))?:'
                  - '^style(\(.*\))?:'
