changelog:
    exclude:
        authors:
            - github-actions[bot]
    include_full_changelog_link: true
    categories:
        - title: "Features"
          labels:
              - feature
              - enhancement
          commits:
              - "feat*"
              - "feature*"
        - title: "Bug Fixes"
          labels:
              - bug
              - fix
          commits:
              - "fix*"
        - title: "Maintenance"
          commits:
              - "chore*"
              - "docs*"
              - "refactor*"
              - "style*"
