changelog:
    exclude:
        authors:
            - github-actions[bot]
    include_full_changelog_link: true
    categories:
        - title: "Features"
          commits:
              - "feat:*"
              - "feat*"
        - title: "Bug Fixes"
          commits:
              - "fix:*"
              - "fix*"
        - title: "Maintenance"
          commits:
              - "chore:*"
