name-template: "osu!tag $RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
    - title: "✨ New Features"
      labels:
          - "feature"
          - "enhancement"
    - title: "🛠 Improvements"
      labels:
          - "improvement"
          - "performance"
    - title: "🐞 Bug Fixes"
      labels:
          - "fix"
          - "bug"
    - title: "🔧 Under the Hood"
      labels:
          - "chore"
          - "internal"

template: |
    # osu!tag $RESOLVED_VERSION – Release Notes

    $CHANGES

    ---
    Thank you for using **osu!tag**!
    Download the new version and enjoy a smoother experience and easier installation.

version-resolver:
    major:
        labels: ["major"]
    minor:
        labels: ["minor"]
    patch:
        labels: ["patch"]
    default: patch
